language: cpp
os: linux
dist: xenial
apt:
  sources:
  - ubuntu-toolchain-r-test
  packages:
  - gcc-8
  - g++-8
  - libboost-all-dev
  - libmagick++-dev
script:
- EXPORT CC=/usr/bin/gcc-8
- EXPORT CXX=/usr/bin/g++-8
- mkdir build
- cd build
- cmake ..
- make
- ./test
