language: cpp
os:
- linux
dist: xenial
compiler:
- clang
addons:
  apt:
    update: true
    packages:
    - imagemagick
    - libboost-dev
script:
- mkdir build
- cd build
- cmake ..
- make
- ./test
